# -*- coding: utf-8 -*-
"""MRS_TarefaSeminário_Grupo_Instagram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WLZ0mLvSKteqvQSPFpB9dQgV64BB2eD-

#Mineração de Redes Sociais
**Professor: Sérgio Nery Simões**

Alunos:

Pablo Simões Nascimento
Fábio Junior Schneider Marcelino
Marcio Rezende
Raphael Nardoto Barboza

Data: 08/07/2019

##Seminário: Estudo de Ferramentas de Redes Sociais Modernas##

# INTRODUÇÃO

##Redes Sociais

Em algumas definições, redes sociais são qualquer tipo de meio que proporcione a comunicação entre pessoas.


Já nos tempos modernos, rede social é como são chamados serviços que, usando a internet, permitem que as pessoas se conectem umas com as outras instantaneamente.


Um dos precursores, ainda na era da internet discada, foi a AOL e seu Instant Messenger, lançado em 1997.


Na mesma época outros mensageiros como o MSN e o ICQ surgiram e se tornaram base para as redes sociais atuais.


MSN ganhou força no Brasil nos anos 2000.


Em 2014 surgiu o Orkut.

##Instagram

Instagram é um serviço de rede social de compartilhamento de fotos e vídeos de propriedade da Facebook, Inc. 


Foi criado por Kevin Systrom e Mike Krieger e lançado em outubro de 2010 exclusivamente no iOS. 

Redes Sociais

Em algumas definições, redes sociais são qualquer tipo de meio que proporcione a comunicação entre pessoas.


Já nos tempos modernos, rede social é como são chamados serviços que, usando a internet, permitem que as pessoas se conectem umas com as outras instantaneamente.


Um dos precursores, ainda na era da internet discada, foi a AOL e seu Instant Messenger, lançado em 1997.


Na mesma época outros mensageiros como o MSN e o ICQ surgiram e se tornaram base para as redes sociais atuais.


MSN ganhou força no Brasil nos anos 2000.


Em 2014 surgiu o Orkut.

![alt text](https://txqsdw.sn.files.1drv.com/y4mm5mS0p6nrHBOmmSHYOqNJDY7ExedX-yKE5TqDFg31qt069M2DDDRdjLepB9MK57mlbPnMdIy-kjjlzB0nCw7rcjjqhO-iVraTXWv-hmb46FRajiCe0Q11rq3uxC5rmjrOYml8F9ph7yrK8tSA8oOKf7wCtHJFcmE5dckuf0rFF4Q8s7YTZ6edRcY0s9wfhbeYM71DQ4HJywMl5guww4Jow?width=729&height=409&cropmode=none)

![alt text](https://txrpsq.sn.files.1drv.com/y4mzNIi23PnWQLrq0CMhL10UyO6Bw-Y-D79UNfVGvskMNQzz2h_V2ujL2b_HjRHc-QfF7Sio9mG85fp9cRGkbw-mC9pjGSwR8DGsxQoSgYjqKGYDXf5qevLwxmk3VLDc1TkZsQZneU8T--MQsriySblAc2mJATHBEInGXtmM6emTVYN7JEpDNjoyyHRD1qWGcjs7sTLZyDl1JncFl6JdwtFJw?width=1024&height=536&cropmode=none)
https://www.goobec.com.br/blog/redes-sociais-dados-estatisticos-2018/

##Publicidade de marcas e popularidade##

"O Instagram está se tornando a plataforma de mídia social número um quando se trata de engajamento de marcas. Quando olhamos para o engajamento em um nível absoluto, o Instagram tem um alcance maior por marcas do que o Facebook, apesar de ter um tamanho de público significativamente menor. Como resultado, vemos as empresas migrando seus investimentos para o Instagram", 

Alexandra Avelar, Country Manager da Socialbakers.

##O que as pessoas postam##
![alt text](https://txs0mg.sn.files.1drv.com/y4mX_s7JN6U8l1xDklShlFrTckBFA0-8hLtpyD-jnoq-HxI_M0JuzT6lAg7-SmhfB89RTgT2QWS_jp4mxXNGhs33oZAaPRTulhiYc_5Z61rMpv40jFa70oga76GRIfVq_y3ustYUP5pqFkFI1wFAgU7siDpRROTzhOEUi4GsKgKudjjw34Swf5-BLcCfI5UCqxeoEOnj0-NzgkTvPzUgDIvNg?width=787&height=327&cropmode=none)

https://projetual.com.br/melhores-tipos-de-posts-no-instagram/

##Como as pessoas mais interagem##

![alt text](https://txtj1a.sn.files.1drv.com/y4myp-v8VffFmeHpJvZ5DjLMydkObNSElnFvRmHoTV9vER3CevTu-ByjXsmJaEMvuqhS6ul1O7n4crKOXECcBKboYr3aG5VhAerWgZF8oH_niUwSTkB8jQgPkCSTHU_it7Az4Iiyjs926A0Mnj0SRPHWRjQ96zxwHgH6v6qabv6S8dGRSmyTCrBkSP5BOS6gWhuBXTkESzEI2bJfpF_5RFCrw?width=773&height=641&cropmode=none)

https://projetual.com.br/melhores-tipos-de-posts-no-instagram/

##Uso de hashtags##
![alt text](https://txrwuw.sn.files.1drv.com/y4mDNCRvJ9gyv6ZCEHH0iNugtw9WDtXp7NVivFZL_yd454CtLPs5zjgkIZptAPdQ1VTlMjCL186iRFlGmUwLdN9P8RKDi8DX4kOBQhuhocEO4Ie27wxqAvUF3gQIZPHbM8shd_nTmw3av628YRsB2UPQ3yqCm4tlaBMT6QVDSRUn7V5XtHxMnAYq7aW-mJaOpgY2JA9WTR7YUPsn3C70DuZhg?width=650&height=389&cropmode=none)

https://www.quintly.com/blog/instagram-study

# Tipo de rede: estudo do Instagram

##Small World  ou Scale Free?##

Um simples modelo representando a relação de “follow” entre usuários mostrou que não segue nenhum modelo particular e é totalmente arbitrário

Fotos tem um importante papel nesta rede social, então faz sentido representar Instagram como um grafo de fotos

Duas abordagens de análise comparativa:
Baseada nos usuários seguindo uns aos outros (“Follow Graph” - dirigido)
Baseada nos likes de usuários sobre a mesma imagem (Like Graph)

##Propriedades em análise##

Coeficiente de Clustering
O coeficiente de clusterização de um nó é o quão completo é o grafo contendo todos os vizinhos desse nó

Graus de Separação
É o número de arestas no caminho mínimo entre dois nós

Normalmente as redes sociais são grafos de mundo pequeno ou livres de escala
Essas duas propriedades definem o tipo do grafo

##Considerações##

Se um grafo tem um valor alto da média do coeficiente de clustering e um valor baixo da média dos graus de separação, então é um grafo do tipo Small World

Se um grafo tem um valor baixo da média do coeficiente de clustering e um valor alto da média dos graus de separação, então é um grafo do tipo Scale Free

##Base de dados e abordagem##

2000 usuários
50000 fotos
Propriedades incluídas: usuários e seus seguidores, usuário que posta fotos (uploader), usuários que deram like em fotos, datas dos posts e tag das fotos.
Subsampling dos grafos principais
Geraram grafos aleatórios de mesmo tamanho das amostras, com as mesmas propriedades, porém, com características de Small World (modelo de Watts Strogatz) e Scale Free (modelo de Albert Barabasi)

##Análise Comparativa: Follow Graph##
![alt text](https://tj8fsq.sn.files.1drv.com/y4mBFydJvWBVugjTitQIZli5fxtEYOEGmaIkHuPFSVtyXgKjYtEdZobefC-0FVzSeeWK1gDgB6KWwoi22wF1SAIf_i25SD5sTXJxIt-sF-siBIBE9rg-_ZjZaaoqw5r9X3EJC9HLfWZ1BGfDNpKvQYEtAVGjJdFjZLRmb5fc0yEoYGSDD727t8li-JNAbGuTayYzqPiILt8j1a0EVWkxtzRFA?width=557&height=387&cropmode=none)

https://www.academia.edu/26984670/Studying_the_behavior_of_Instagram_network

##Análise Comparativa: Like Graph##
![alt text](https://tjpgvq.sn.files.1drv.com/y4m575iOf0mOhfClhv4QO1Umy6Tx6lznGkB7t6iuJ1zsPkhje9Ynd3Rm_Xo3AnmJXPpv8Nxl_ejaxk8y8lX2AuDnw8MC9GAXfq_BXNvRXf9UIXZEOScGLVXTNcXkeyKLb73c2Sz0n7CX-YFgxOFu6KXL2u7RKikE8ilfSnmRY21Fx96VghJyT3oUAB_dFb--Xy_VO8EQO93WCsiaMA3ORmZ8Q?width=563&height=399&cropmode=none)

https://www.academia.edu/26984670/Studying_the_behavior_of_Instagram_network

##Conclusão da análise comparativa##

O estudo mostra que a rede do Instagram, diferente da maioria das redes sociais, não é centrada no usuário, mas os clusters são formados em torno do conteúdo postado por eles
Pessoas que gostam das mesmas fotos formam fortes agrupamentos em clusters
O grafo de fotos tendeu a ser uma rede Small World 
Isso ajuda a determinar a importância dos nós em termos de alta conectividade e alta afinidade

#Instagram - Prática#
##GraphAPI##
![alt text](https://tjqpxw.sn.files.1drv.com/y4my5jaVOnL5W5tgoFJK1Za0qI7JAJBNCothd21z9UYimhvvz2t8zHYlcrsAuTYGk260z_EKCJs8ciPWk5BO7PsZ8uJE5nkN0GwRlFlcxuT2JeJOI3BZEAeZHOjvKT5X_OlP3DmaUbrOp9cpMxUKg0biD_AxqlYe-SZsI4b28usO6nefU8VR-U1PuwOHq0996ZJ8HSVWhu4Ojp_4JpIt1yqJA?width=785&height=442&cropmode=none)

![alt text](https://tj9q1a.sn.files.1drv.com/y4mQs8fcnL62WLJsSw8AxrI1ht7iChrsPyDVs7RZaQYA8_qX3pycx_3SJ66IuzHXcywNo3z13SatQzv1z_-tsmvjVYnRBALpkqbZREpybGKBYEn3YevtRs43o3QsM3ggyCldjxw4YLpFRXQAD2yRptNFSHktxPh-Mfr8Ot5O9xaJIfVU6yObX7IlPFH3kq3IlETpi-3rg2UpyVlA5wUqYnq-g?width=785&height=442&cropmode=none)

![alt text](https://tj9xgw.sn.files.1drv.com/y4mYgVgbEJx1aYIOreljLfO40kg1HVyfSOywjHE6l_fjzaHfW8uxNqduNT3PkThQ9F5viaPMO0Pet5-F_Qi2aIBhoGNVnIvK069FeYRTM82v8KnZjmEMJ5i7nhlssA7OOuAbYcYPdQqJqaO5W1xyY5gXqYozzYUQzUNZ-qCkXmgBJPv12uivIUNJSxeY7IHDWltBKyyg4KnbTKqCUrSX8mlNw?width=785&height=442&cropmode=none)

![alt text](https://tj8mka.sn.files.1drv.com/y4m6NVyf3IFiziOalf0MWryoYFEPFyQMvWXIT58n1UYZm3aAxj9kcVb3qIXUobwVYN8FBswFcO-yBLPhYTuBqviavNOKJdpLYPmceu-r1DKZ9h3RVWnh2zyWTU8nNZegZyo5Mgnpz20NIgsodUhwd6pS9We_eLQwRPS7Kk6st3CJ1r6rmlE57HyvSLeYkPYmgQ3YCaiVAuKaYoHdPZ8osnIhA?width=876&height=442&cropmode=none)

# Instagram	 - Restrições

**Plataforma de API do Instagram: descontinuação**

“Nós estaremos desaprovando a antiga Plataforma da API do Instagram em três fases, com descontinuidade completa ocorrendo no início de 2020.
Os seguintes estarão disponíveis até 31 de julho de 2018 :
Lista de seguidores - para ler a lista de seguidores e usuários seguidos
Relacionamentos - para seguir e deixar de seguir as contas em nome de um usuário
Comentando sobre o conteúdo público - para postar e excluir comentários em nome de um usuário na mídia pública”

Os seguintes recursos estarão disponíveis até 11 de dezembro de 2018 :
Comentando - para postar e excluir comentários em nome de um usuário em mídia de propriedade
Conteúdo público - para ler qualquer informação de perfil público e mídia em nome de um usuário
Curtir- Curtir e Descurtir mídia em nome de um usuário
Assinaturas - para receber notificações quando a mídia é postada

O Instagram, assim como Facebook, parou de receber submissões para novos aplicativos parceiros da plataforma. Desenvolvedores disseram que a mudança não estava agendada, nem mesmo foram notificados sobre a as novidades da API para que pudessem adaptar seus aplicativos para que continuem funcionando no Instagram.

![alt text](https://tj87mg.sn.files.1drv.com/y4mo22cse7p_Pp3zplk_BZLegZgPt96lEmyXDWOP-u0iAx0r5-ANtwkDoXVNwyyrvkUya0vQMHrxfDYUjsTMU0WMDhrTsCEZWuCgpd5_L6BKylMzSIe9jOo4gRo6XDj_lRVy8SSwhmAP-1FHbrig3FG7JMkKvZbyRKk-lpyh_l3KvYSebkaV51OFaC-vIVYZHVDl93DnZ_4FONFjkjEzb2JDQ?width=928&height=426&cropmode=none)

![alt text](https://tjqwpg.sn.files.1drv.com/y4mwlgVjNagK8RYWtXXPzVE9olrWv-f8pDTlYxRTjE-LUbxLQ1_tU8wPSeVMjok8rSy14akTgfITCZHkZ1sfgV9rcm2g5UAzhZ8F19HuZaIuqn9LKHmrGIHcUZSrhQQkQvUCOYfY-eU-zea-OY5-UdUBRrljJ73P1vMz3WLAmSGmmsk24suJVLyzj9pTRuj7mcC0sFAp-eX_BwLnZGRU5JeKQ?width=928&height=402&cropmode=none)

# Prática com o InstagramAPI

---


Essa é uma versão não oficial da API do Instagram, pois a versão oficial, está com o acesso bloqueado.

I)Instalando o Pacote da API
"""

pip install InstagramApi

"""Importando a biblioteca"""

from InstagramAPI import InstagramAPI

"""Definindo a função que recupera os seguidores da página"""

from InstagramAPI import InstagramAPI
import time
from datetime import datetime

username = 'youusername'
pwd = 'yourpassword'


API = InstagramAPI(username,pwd)
API.login()
user_id  = API.username_id

API.getUsernameInfo(user_id)
API.LastJson
following   = []
next_max_id = True
while next_max_id:
    print(next_max_id)
    #first iteration hack
    if next_max_id == True: next_max_id=''
    _ = API.getUserFollowings(user_id,maxid=next_max_id)
    following.extend ( API.LastJson.get('users',[]))
    next_max_id = API.LastJson.get('next_max_id','')

len(following)
unique_following = {
    f['pk'] : f
    for f in following
}
len(unique_following)

"""Função que recupera os posts da conta fornecida"""

def get_my_posts(api):
    '''Retrieve all posts from own profile'''
    my_posts = []
    has_more_posts = True
    max_id= ''

    while has_more_posts:
        api.getSelfUserFeed(maxid=max_id)
        if api.LastJson['more_available'] is not True:
            has_more_posts = False #stop condition

        max_id = api.LastJson.get('next_max_id','')
        my_posts.extend(api.LastJson['items']) #merge lists
        time.sleep(2) # slows down to avoid flooding

        if has_more_posts:
            print(str(len(my_posts)) + ' posts retrieved so far...')

    print('Total posts retrieved: ' + str(len(my_posts)))
    
    return my_posts

"""Utilizando a função de recuperar os posts"""

my_posts = get_my_posts(API)

my_posts

"""Função que recupera quem deu like nas postagens"""

def get_posts_likers(api, my_posts):
    '''Retrieve all likers on all posts'''
    
    likers = []
    
    print('wait %.1f minutes' % (len(my_posts)*2/60.))
    for i in range(len(my_posts)):
        m_id = my_posts[i]['id']
        api.getMediaLikers(m_id)
        
        likers += [api.LastJson]
        
        # Include post_id in likers dict list
        likers[i]['post_id'] = m_id
        
        time.sleep(2)
    print('done')
    
    return likers

"""Utilizando a função"""

likers = get_posts_likers(API, my_posts)

likers

"""Função que recupera as mídias com os ids que são passados"""

API.getUsernameInfo(user_id)
n_media = API.LastJson['user']['media_count']

media_ids = []
max_id = ''
for i in range(int(n_media/18+1)): 
    API.getUserFeed(usernameId=user_id, maxid = max_id)
    media_ids += API.LastJson['items'] 
    if API.LastJson['more_available']==False:
        print("no more avaliable")            
        break
    max_id = API.LastJson['next_max_id'] 
    print( i, "   next media id = ", max_id, "  ", len(media_ids))
    time.sleep(3)

"""Trecho que retorns o relacionamentos de seguidores"""

import pandas as pd
import tqdm as tqdm

API.getSelfUsernameInfo()
result = API.LastJson
user_id = result['user']['pk'] # my own personal user id
me = result['user']['full_name'] # my own personal username

API.getSelfUsersFollowing()
result = API.LastJson
follow_relationships = []
for user in tqdm(result['users']):
    followed_user_id = user['pk'] 
    followed_user_name = user['full_name']
    follow_relationships.append((user_id, followed_user_id, me, followed_user_name))
    API.getUserFollowings(followed_user_id)
    result2 = API.LastJson
    if result2.get('users') is not None:
        for user2 in result2['users']:
            follow_relationships.append((followed_user_id, user2['pk'],
                                         followed_user_name, user2['full_name']))

"""Transforma o resultado em dataframe"""

df = pd.DataFrame(follow_relationships,
                  columns=['src_id','dst_id', 'src_name', 'dst_name'])

df.head

df.describe()

"""Cria um grafo com as informações do dataframe gerado do seguidores"""

import networkx as nx

nx.draw(G2, with_labels = True)
plt.show()

def DataFrame2Graph(dataframe):
    G = nx.Graph()
    for i in range(dataframe.shape[0]):
        # retrieve the first and the second column for each line
        u,v = dataframe[['src_name','dst_name']].iloc[i]
        #adds the edge (u,v) to the graph 
        G.add_edge(u,v)
    
    return G

G1 = DataFrame2Graph(df)

"""Visualização do grafo gerado"""

import matplotlib.pyplot as plt

nx.draw(G1, with_labels = True)
plt.show()

"""Exportando para para CSV para criar a visualização no Cytoscape"""

df.to_csv("intagram2.csv")

"""Exibição da rede no Cytoscape

![alt text](https://txr3ag.sn.files.1drv.com/y4mSxnpJblDot12x2Pfwqz5QfWvZniG72gdfurh-VZ16RYTAkDx1BMV-prC5-AiQTKE6T-WCo6vml3mM5A5NbVAAz_df4lHdwI5WsrIBNaBJM02630uwZidU3f2xHtN_zPG-nC_FNFP6-5yxbd0M_MBeZA4dry8u1H1gZPGwAHriE5QnQ4AXdI8W0f1KDQJrejrdI8NcNftmMWrq576YBll6A?width=959&height=433&cropmode=none)
"""